#ifndef __LIDAR_REGISTERS_H__
#define __LIDAR_REGISTERS_H__

#define LIDAR_CONTROL_REG 0x00
#define LIDAR_STATUS_REG 0x01
#define LIDAR_TARGET_ANGLE_REG 0x02

#define LIDAR_MOTOR_SPEED_REG    0x10
#define LIDAR_LIDAR_IP_REG       0x11
#define LIDAR_DEST_IP_REG        0x12
#define LIDAR_MAC_ADDR_REG1      0x13
#define LIDAR_MAC_ADDR_REG2      0x14
#define LIDAR_PORT1_PORT2_REG    0x15
#define LIDAR_PORT3_PORT4_REG    0x16
#define LIDAR_FOV_SET_REG        0x17
#define LIDAR_MOT_PHASE_REG      0x18
#define LIDAR_TOP_FRM_REG1       0x19
#define LIDAR_TOP_FRM_REG2       0X1A
#define LIDAR_BOT_FRM_REG1       0X1B
#define LIDAR_BOT_FRM_REG2       0X1C
#define LIDAR_COR_VERT_ANG_REG16 0X1D
#define LIDAR_COR_VERT_ANG_REG15 0X1E
#define LIDAR_COR_VERT_ANG_REG14 0X1F
#define LIDAR_COR_VERT_ANG_REG13 0X20
#define LIDAR_COR_VERT_ANG_REG12 0X21
#define LIDAR_COR_VERT_ANG_REG11 0X22
#define LIDAR_COR_VERT_ANG_REG10 0X23
#define LIDAR_COR_VERT_ANG_REG9  0X24
#define LIDAR_COR_VERT_ANG_REG8  0X25
#define LIDAR_COR_VERT_ANG_REG7  0X26
#define LIDAR_COR_VERT_ANG_REG6  0X27
#define LIDAR_COR_VERT_ANG_REG5  0X28
#define LIDAR_COR_VERT_ANG_REG4  0X29
#define LIDAR_COR_VERT_ANG_REG3  0X2A
#define LIDAR_COR_VERT_ANG_REG2  0X2B
#define LIDAR_COR_VERT_ANG_REG1  0X2C
#define LIDAR_SN_REG1            0X2D
#define LIDAR_SN_REG2            0X2E
#define LIDAR_SOFTWARE_VER_REG   0X2F
#define LIDAR_UTC_TIME_REG1      0X30
#define LIDAR_UTC_TIME_REG2      0X31
#define LIDAR_UTC_TIME_REG3      0X32
#define LIDAR_STATUS_IDATA_REG1  0X33
#define LIDAR_STATUS_IDATA_REG2  0X34
#define LIDAR_STATUS_VDATA_REG1  0X35
#define LIDAR_STATUS_VDATA_REG2  0X36
#define LIDAR_STATUS_VDATA_REG3  0X37
#define LIDAR_FALT_DIGS_REG1     0X38
#define LIDAR_FALT_DIGS_REG2     0X39
#define LIDAR_FALT_DIGS_REG3     0X3A
#define LIDAR_FALT_DIGS_REG4     0X3B
#define LIDAR_FALT_DIGS_REG5     0X3C
#define LIDAR_ECHO_MODE_REG      0X3D

#define MAC_CONTROL_REG          0X00
#define MAC_STATUS_REG           0X01
#define MAC_LOCAL_MAC_L32_REG    0X02
#define MAC_LOCAL_MAC_H16_REG    0X03
#define MAC_LOCAL_IP_REG         0X04
#define MAC_MSOP_UDP_PORT_REG    0X05
#define MAC_DIFOP_UDP_PORT_REG   0X06
#define MAC_GATEWAY_IP_REG       0X07
#define MAC_SUBNET_MASK_REG      0X08

#endif
